package com.as.gui;

import com.as.bl.PatientsHandler;
import com.as.main.BaseForm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Main extends BaseForm {
    private JPanel contentPane;
    private JButton btnInsertPatientInMiniForm;
    private JButton btnInsertPatientInComprehensiveRegistrationForm;
    private JButton btnGetPatients;
    private JButton doctorManagementButton;
    private JButton insertBillButton;
    private JButton insertAppointmentButton;


    private static final PatientsHandler PH = new PatientsHandler();

    public Main() throws HeadlessException {
        super("Main menu", 500, 500);

        setContentPane(contentPane);
        btnInsertPatientInMiniForm.addActionListener(e -> {
            MiniForm mf = new MiniForm();
            mf.setVisible(true);
        });

        btnInsertPatientInComprehensiveRegistrationForm.addActionListener(e -> {
            ComprehensiveForm cf = new ComprehensiveForm();
            cf.setVisible(true);
        });

        btnGetPatients.addActionListener(e -> {
            ViewPatients vp = new ViewPatients();
            vp.setVisible(true);
        });

        doctorManagementButton.addActionListener(e -> {
            DoctorManagement dm = new DoctorManagement();
            dm.setVisible(true);
        });

        insertAppointmentButton.addActionListener(e -> {
            AppointmentForm af = new AppointmentForm();
            af.setVisible(true);
        });


        insertBillButton.addActionListener(e -> {
            BillForm bf = new BillForm();
            bf.setVisible(true);
        });
    }

    public static void start() {
        SwingUtilities.invokeLater(() -> {
            Main window = new Main();
            window.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
            window.setVisible(true);
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        btnInsertPatientInMiniForm = new JButton();
        btnInsertPatientInMiniForm.setText("Insert patient(mini form)");
        contentPane.add(btnInsertPatientInMiniForm, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnInsertPatientInComprehensiveRegistrationForm = new JButton();
        btnInsertPatientInComprehensiveRegistrationForm.setText("Insert patient (comprehensive form)");
        contentPane.add(btnInsertPatientInComprehensiveRegistrationForm, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnGetPatients = new JButton();
        btnGetPatients.setText("Get patients");
        contentPane.add(btnGetPatients, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        doctorManagementButton = new JButton();
        doctorManagementButton.setText("Doctor management");
        contentPane.add(doctorManagementButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        insertBillButton = new JButton();
        insertBillButton.setText("Insert bill");
        contentPane.add(insertBillButton, new com.intellij.uiDesigner.core.GridConstraints(5, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        insertAppointmentButton = new JButton();
        insertAppointmentButton.setText("Insert appointment");
        contentPane.add(insertAppointmentButton, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
